"""chaged the status

Revision ID: 5680bf08d656
Revises: fc14773ebc98
Create Date: 2025-11-10 23:51:29.387315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5680bf08d656'
down_revision: Union[str, Sequence[str], None] = 'fc14773ebc98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'status')
    # ### end Alembic commands ###
