"""Added cascade to model for servicee and boking

Revision ID: c472bf2e8d4c
Revises: 3f839b9592bb
Create Date: 2025-12-23 10:55:51.963393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c472bf2e8d4c'
down_revision: Union[str, Sequence[str], None] = '3f839b9592bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('booking_user_id_fkey'), 'booking', type_='foreignkey')
    op.create_foreign_key(None, 'booking', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('service_admin_id_fkey'), 'service', type_='foreignkey')
    op.create_foreign_key(None, 'service', 'user', ['admin_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.create_foreign_key(op.f('service_admin_id_fkey'), 'service', 'user', ['admin_id'], ['id'])
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.create_foreign_key(op.f('booking_user_id_fkey'), 'booking', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
